# Generated by Django 5.1.7 on 2025-03-26 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_alter_message_timestamp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
