# Generated by Django 5.1.7 on 2025-03-26 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LostNFound', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lostitem',
            name='reward',
        ),
    ]
