# Generated by Django 5.1.7 on 2025-03-24 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LostNFound', '0004_rename_started_at_chat_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
