# Generated by Django 5.1.7 on 2025-03-24 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LostNFound', '0007_notification_delete_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
